### ISSUE TITLE
发现可能原因.

### ISSUE THREAD

**Issue by xrr2016** [LukerSpringtree/demoProject#1]
1. app/modules/signin.server.model.js 这个文件没有导出User这个model, 添加
```
module.exports = User
```
2. app/controllers/signin.server.controller.js 这个文件没有导入User model, 添加
```
const User = require('../modules/signin.server.model ')
```
先导出, 在导入, 看能否解决问题.

**Comment by LukerSpringtree** [comment]
@xrr2016    解决了 !
谢谢!
